<nav class="navbar navbar-expand bg-body-tertiary mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" href="<?= route('root') ?>">Eventos do Câmpus</a>
        <ul class="navbar-nav">
            <?php if ($this->currentUser() === null) : ?>
                <li class="nav-item">
                    <a class="nav-link" href="<?= route('users.login') ?>">Login</a>
                </li>
            <?php else : ?>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                        <?= $this->currentUser()->email ?>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="<?= route('users.logout') ?>">Sair</a></li>
                    </ul>
                </li>
            <?php endif; ?>
        </ul>
    </div>
</nav>
